version: '3'
services:
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: training
    ports:
      - 3306:3306

  tool:
    image: phpmyadmin/phpmyadmin:5
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db #mysqlサービス名を指定
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80